// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDThhvN05vCK6ulFFVmqFqN685y2p9xABw',
    appId: '1:1051625822157:web:ead1350e18bfaf82fe1684',
    messagingSenderId: '1051625822157',
    projectId: 'house-app-2084f',
    authDomain: 'house-app-2084f.firebaseapp.com',
    storageBucket: 'house-app-2084f.appspot.com',
    measurementId: 'G-VX9LNHW1CK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_W0zN7LlYkPdCBhGxsptWKo43j2SbYHY',
    appId: '1:1051625822157:android:9ef2a8d572cd9846fe1684',
    messagingSenderId: '1051625822157',
    projectId: 'house-app-2084f',
    storageBucket: 'house-app-2084f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6x84_BKP4LH9IU7TcrZRYf9TrY5fjgHc',
    appId: '1:1051625822157:ios:49ee6b65716570c6fe1684',
    messagingSenderId: '1051625822157',
    projectId: 'house-app-2084f',
    storageBucket: 'house-app-2084f.appspot.com',
    iosBundleId: 'com.houseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6x84_BKP4LH9IU7TcrZRYf9TrY5fjgHc',
    appId: '1:1051625822157:ios:49ee6b65716570c6fe1684',
    messagingSenderId: '1051625822157',
    projectId: 'house-app-2084f',
    storageBucket: 'house-app-2084f.appspot.com',
    iosBundleId: 'com.houseapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDThhvN05vCK6ulFFVmqFqN685y2p9xABw',
    appId: '1:1051625822157:web:c11a5fec957ef4adfe1684',
    messagingSenderId: '1051625822157',
    projectId: 'house-app-2084f',
    authDomain: 'house-app-2084f.firebaseapp.com',
    storageBucket: 'house-app-2084f.appspot.com',
    measurementId: 'G-1RJS0VBP62',
  );

}